const platforms = [
  { name: 'TikTok', handle: '@domg.o', image: '/images/dom-05.jpg', href: 'https://www.tiktok.com/@domg.o', accent: 'border-b-[#25F4EE]', note: 'The main conversation' },
  { name: 'Instagram', handle: '@domg.0', image: '/images/dom-04.jpg', href: 'https://www.instagram.com/domg.0/', accent: 'border-b-[#C13584]', note: 'Reels, stories and more' },
  { name: 'YouTube', handle: '@domg.o', image: '/images/dom-06.jpg', href: 'https://www.youtube.com/@domg.o', accent: 'border-b-[#FF0000]', note: 'Longer-form features' },
] as const;

export default function About() {
  return <section id="about" className="scroll-mt-20 bg-ink/[.035] py-16 sm:py-24"><div className="reveal mx-auto max-w-7xl px-5 sm:px-8">
    <div className="grid items-start gap-10 md:grid-cols-[.8fr_1.2fr]"><div className="max-w-sm rotate-[-1deg] border border-ink/15 bg-paper-bright p-2 shadow-lg"><img className="aspect-square w-full object-cover" src="/images/dom-03.png" alt="Dom, creator behind @domg.o" /><p className="px-2 pb-1 pt-3 text-center font-mono text-[10px] font-bold uppercase tracking-wider text-ink-soft">Dom · creator studies, class of now</p></div>
      <div><p className="font-mono text-xs font-bold uppercase tracking-[.16em] text-biro">About Dom</p><h2 className="mt-3 font-display text-4xl font-extrabold leading-[1.02] tracking-[-.045em] sm:text-5xl">Built for the shift from uni to work.</h2><p className="my-6 max-w-xl border-l-4 border-biro pl-5 font-serif text-2xl italic leading-tight">Funny, relatable and just direct enough to make the group chat pause.</p><div className="max-w-2xl space-y-4 leading-7 text-ink-soft"><p>I make social content about student life, early careers and the awkward bits everyone recognises but rarely says out loud.</p><p>My work is audience-first: useful for a brand, natural in-feed, and made for people navigating their first big adult decisions.</p></div><div className="mt-7 flex flex-wrap gap-3"><a href="https://www.tiktok.com/@domg.o" target="_blank" rel="noreferrer" className="border-2 border-ink px-4 py-2 font-body text-xs font-bold uppercase tracking-wide transition hover:bg-ink hover:text-paper">TikTok · @domg.o ↗</a><a href="https://www.instagram.com/domg.0/" target="_blank" rel="noreferrer" className="border-2 border-ink px-4 py-2 font-body text-xs font-bold uppercase tracking-wide transition hover:bg-ink hover:text-paper">Instagram · @domg.0 ↗</a></div><p className="mt-6 font-mono text-[10px] uppercase tracking-wider text-ink-soft">Also open to talent representation.</p></div>
    </div>
    <div className="mt-16 border-t-2 border-ink pt-8"><div className="flex flex-wrap items-end justify-between gap-4"><div><p className="font-mono text-xs font-bold uppercase tracking-[.16em] text-biro">Follow the work</p><h3 className="mt-2 font-display text-3xl tracking-[-.045em]">The community, platform by platform.</h3></div><p className="max-w-sm text-sm leading-6 text-ink-soft">Different formats, one recognisable voice. Follow along wherever your audience already is.</p></div><div className="mt-7 grid gap-5 sm:grid-cols-3">{platforms.map((platform, index) => <a key={platform.name} href={platform.href} target="_blank" rel="noreferrer" className={`group overflow-hidden border-2 border-ink border-b-6 bg-paper-bright transition hover:-translate-y-1 hover:shadow-xl ${platform.accent} ${index === 1 ? 'sm:translate-y-5' : ''}`}><img className="aspect-[4/5] w-full object-cover transition duration-500 group-hover:scale-[1.03]" src={platform.image} alt={`${platform.name} content by ${platform.handle}`} /><div className="flex items-end justify-between gap-3 p-4"><div><strong className="block font-display text-base tracking-[-.05em]">{platform.name}</strong><span className="mt-1 block font-mono text-[10px] font-bold text-ink-soft">{platform.handle}</span><span className="mt-3 block font-body text-xs text-ink-soft">{platform.note}</span></div><span className="font-mono text-sm text-biro">↗</span></div></a>)}</div></div>
  </div></section>;
}
