const channels = [
  ['Instagram', 'https://www.instagram.com/domg.0/'],
  ['TikTok', 'https://www.tiktok.com/@domg.o'],
  ['YouTube', 'https://www.youtube.com/@domg.o'],
] as const;

export default function Contact() {
  return <section id="contact" className="scroll-mt-20 pb-16 sm:pb-24"><div className="reveal mx-auto max-w-7xl px-5 sm:px-8"><div className="grid bg-biro text-white lg:grid-cols-[1.1fr_.9fr]">
    <div className="p-7 sm:p-14"><p className="font-mono text-xs font-bold uppercase tracking-[.16em] text-white/80">Let&apos;s work together</p><h2 className="mt-4 max-w-xl font-display font-black text-4xl leading-[.98] tracking-[-.045em] sm:text-5xl">Let&apos;s make the grade.</h2><p className="mt-3 font-serif text-xl italic text-white/80">Send the brief. I&apos;ll bring the point of view.</p><p className="mt-5 max-w-xl leading-7 text-white/85">For brand partnerships, UGC and social takeovers. Email is the fastest route; a detailed media kit and rate card are available on request.</p><a href="mailto:dom@domgo.co.uk?subject=Brand%20partnership%20brief" className="mt-8 inline-block border-2 border-white bg-white px-4 py-3 font-body text-xs font-bold uppercase tracking-wide text-biro transition hover:bg-ink hover:text-paper">Email a brief · dom@domgo.co.uk</a><div className="mt-8 flex flex-wrap gap-3">{channels.map(([label, href]) => <a key={label} href={href} target="_blank" rel="noreferrer" className="font-mono text-[10px] font-bold uppercase tracking-wider text-white/85 underline decoration-white/40 underline-offset-4 hover:text-white">{label} ↗</a>)}</div><p className="mt-8 font-mono text-[10px] uppercase tracking-wider text-white/70">Representation enquiries welcome via the same email.</p></div>
    <form action="mailto:dom@domgo.co.uk" method="post" encType="text/plain" className="border-t-2 border-white/30 bg-ink p-7 sm:p-10 lg:border-l-2 lg:border-t-0"><p className="font-mono text-[10px] font-bold uppercase tracking-wider text-biro-soft">Brief starter</p><p className="mt-2 text-sm text-paper/70">A few details make a faster first reply.</p><div className="mt-6 grid gap-4"><label className="font-mono text-[10px] font-bold uppercase tracking-wider">Brand / agency<input required name="Brand or agency" className="mt-2 w-full border border-paper/40 bg-transparent px-3 py-3 font-body text-sm normal-case tracking-normal text-paper outline-none focus:border-biro-soft" /></label><label className="font-mono text-[10px] font-bold uppercase tracking-wider">Campaign details<textarea required name="Campaign details" rows={3} placeholder="Dates, deliverables, budget band" className="mt-2 w-full resize-none border border-paper/40 bg-transparent px-3 py-3 font-body text-sm normal-case tracking-normal text-paper placeholder:text-paper/40 outline-none focus:border-biro-soft" /></label><button type="submit" className="w-fit border-2 border-paper bg-paper px-4 py-3 font-body text-xs font-bold uppercase tracking-wide text-ink transition hover:bg-biro-soft">Start an email ↗</button></div></form>
  </div></div></section>;
}
