const platforms = [
  { name: 'TikTok', handle: '@domg.o', followers: '72,468', engagement: '5.8%', age: '85.9%', accent: 'bg-[#25F4EE]', label: '18–34 audience' },
  { name: 'Instagram', handle: '@domg.0', followers: '18,378', engagement: '6.4%', age: '84.5%', accent: 'bg-[#E7468A]', label: '18–34 audience' },
] as const;

export default function Stats() {
  return <section id="audience" className="scroll-mt-20 border-y-2 border-ink bg-ink py-16 text-paper sm:py-24"><div className="mx-auto max-w-7xl px-5 sm:px-8">
    <div className="reveal grid gap-10 lg:grid-cols-[.85fr_1.15fr]"><div><p className="font-mono text-xs font-bold uppercase tracking-[.18em] text-biro-soft">Audience, at a glance</p><h2 className="mt-4 font-display text-4xl leading-[1.02] tracking-[-.065em] sm:text-5xl">An audience growing up in public.</h2><p className="mt-6 max-w-md leading-7 text-paper/70">Built with students, now moving alongside them into first jobs, first paycheques, and all the decisions in between.</p><div className="mt-9 border-l-2 border-biro-soft pl-4 font-serif text-xl italic text-paper/85">UK-first. English-speaking. Not afraid of an opinion.</div></div>
      <div className="grid gap-4 sm:grid-cols-2">{platforms.map(platform => <article key={platform.name} className="relative overflow-hidden border border-paper/30 bg-paper/[.06] p-6 transition hover:-translate-y-1 hover:bg-paper/[.1]"><span className={`absolute right-0 top-0 h-2 w-24 ${platform.accent}`} /><p className="font-mono text-[10px] font-bold uppercase tracking-[.16em] text-paper/60">{platform.name} · {platform.handle}</p><strong className="mt-6 block font-display text-4xl tracking-[-.08em]">{platform.followers}</strong><span className="mt-1 block font-mono text-[10px] uppercase tracking-wider text-paper/60">followers</span><div className="mt-8 grid grid-cols-2 gap-3 border-t border-paper/20 pt-4"><div><b className="font-display text-xl tracking-[-.06em] text-biro-soft">{platform.engagement}</b><span className="mt-1 block font-mono text-[9px] uppercase tracking-wider text-paper/55">engagement</span></div><div><b className="font-display text-xl tracking-[-.06em] text-biro-soft">{platform.age}</b><span className="mt-1 block font-mono text-[9px] uppercase tracking-wider text-paper/55">{platform.label}</span></div></div></article>)}</div>
    </div><div className="reveal mt-10 grid gap-3 border-t border-paper/20 pt-6 text-center sm:grid-cols-3"><p className="font-mono text-[10px] uppercase tracking-wider text-paper/60">44–48% UK audience</p><p className="font-mono text-[10px] uppercase tracking-wider text-paper/60">Platform analytics, no rounding up</p><a href="#contact" className="font-mono text-[10px] font-bold uppercase tracking-wider text-biro-soft underline underline-offset-4">Request the full media kit ↗</a></div>
  </div></section>;
}
