type Metric = { value: string; label: string };
const tiktok: Metric[] = [{ value: '72,468', label: 'Followers' }, { value: '37.2M', label: 'Post views' }, { value: '4.2M', label: 'Likes' }, { value: '1M', label: 'Shares' }];
const instagram: Metric[] = [{ value: '18,378', label: 'Followers' }, { value: '4.9M', label: 'Views' }, { value: '2.94M', label: 'Accounts reached' }, { value: '592K', label: 'Interactions' }, { value: '4.8M', label: 'Reels views' }];
const audience = [{ title: 'Age range · TikTok', data: [['18–24', 48.5], ['25–34', 37.4], ['35–44', 8.1], ['45+', 6]] }, { title: 'Age range · Instagram', data: [['18–24', 55.9], ['25–34', 28.6], ['35–44', 6.8], ['45+', 6.4]] }, { title: 'Top locations · TikTok', data: [['United Kingdom', 44.2], ['United States', 8.7], ['Canada', 2.3]] }, { title: 'Top locations · Instagram', data: [['United Kingdom', 48], ['United States', 11.3], ['Canada', 3.1]] }] as const;

function MetricGrid({ metrics }: { metrics: Metric[] }) {
  const cols = metrics.length >= 5 ? 'lg:grid-cols-5' : 'lg:grid-cols-4';
  return <div className={`grid gap-3 sm:grid-cols-2 ${cols}`}>{metrics.map(metric => <div key={metric.label} className="border-2 border-ink bg-paper-bright p-5 text-center transition hover:-translate-y-1 hover:shadow-lg"><strong className="block font-display text-2xl font-extrabold tracking-[-.07em] text-biro">{metric.value}</strong><span className="mt-2 block font-mono text-[10px] font-bold uppercase tracking-wider text-ink-soft">{metric.label}</span></div>)}</div>;
}

export default function Stats() {
  return <section id="analytics" className="scroll-mt-20 bg-ink/[.035] py-16 sm:py-24"><div className="mx-auto max-w-7xl px-5 sm:px-8"><p className="font-mono text-xs font-bold uppercase tracking-[.16em] text-biro">Audience snapshot · TikTok &amp; Instagram</p><h2 className="mt-3 font-display text-3xl font-extrabold tracking-[-.06em] sm:text-4xl">Straight from the app.</h2><p className="mt-3 text-ink-soft">Pulled directly from platform analytics, no rounding up.</p><div className="mt-10"><p className="mb-3 font-mono text-xs font-bold uppercase tracking-wider text-biro">TikTok · last 12 months</p><MetricGrid metrics={tiktok} /></div><div className="mt-7"><p className="mb-3 font-mono text-xs font-bold uppercase tracking-wider text-biro">Instagram · last 90 days</p><MetricGrid metrics={instagram} /></div><div className="mt-12 grid gap-8 sm:grid-cols-2">{audience.map(group => <div key={group.title}><h3 className="font-mono text-xs font-bold uppercase tracking-wider">{group.title}</h3><div className="mt-4 space-y-3">{group.data.map(([label, value]) => <div key={label}><div className="mb-1 flex justify-between font-mono text-xs"><span>{label}</span><b className="text-biro">{value}%</b></div><div className="h-2 overflow-hidden rounded-full bg-ink/10"><div className="h-full rounded-full bg-biro" style={{ width: `${value}%` }} /></div></div>)}</div></div>)}</div><p className="mt-9 font-mono text-xs text-ink-soft">Full breakdown by gender, hourly activity and platform available on request.</p></div></section>;
}